# Generated by Django 6.0.5 on 2026-05-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_voto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voluntario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telemovel', models.CharField(max_length=20)),
                ('dias', models.CharField(max_length=200)),
                ('data_candidatura', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
